/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package phanmenquanlybatdongsan;

import Data.KhachHang;
import Data.PicPanel;
import Modify.KetNoi;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public final class QuanLyKhachHang extends javax.swing.JInternalFrame {
    KetNoi ketnoi;
    int index;
    ArrayList<KhachHang> listKH = new ArrayList<>();
    /**
     * Creates new form QuanLyKhachHang
     * @throws java.lang.ClassNotFoundException
     */
    public QuanLyKhachHang() throws ClassNotFoundException {
        initComponents();
        setSize(1000, 540);
        PicPanel pic = new PicPanel("C:\\bg.jpg");
        pic.setBounds(0, 0, 1000, 700);
        add(pic);
        rdoNam_Khachhang.setSelected(true);
        btnSua_Khachhang.setEnabled(false);
        btnXoa_Khachhang.setEnabled(false);
        try {
            ketnoi = new KetNoi();
            ketnoi.ketnoi();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(QuanLyNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            filltotable();
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyKhachHang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void openKhachHang() throws ClassNotFoundException {
        QuanLyKhachHang quanLyKhachHang = new QuanLyKhachHang();
        quanLyKhachHang.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rdoNam_Khachhang = new javax.swing.JRadioButton();
        rdoNu_Khachhang = new javax.swing.JRadioButton();
        txtHoTen_Khachhang = new javax.swing.JTextField();
        txtMa_Khachhang = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtSoDT_Khachhang = new javax.swing.JTextField();
        txtCMND_Khachhang = new javax.swing.JTextField();
        txtEmail_Khachhang = new javax.swing.JTextField();
        txtNgaySinh_Khachhang = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        btnThoat_Khachhang = new javax.swing.JButton();
        btnMoi_Khachhang = new javax.swing.JButton();
        btnXoa_Khachhang = new javax.swing.JButton();
        btnSua_Khachhang = new javax.swing.JButton();
        btnThem_Khachhang = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Khachhang = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();

        setResizable(true);
        setTitle("Quản Lý Khách Hàng");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông Tin Khách Hàng"));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("Mã :");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Họ Tên :");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("Ngày Sinh :");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setText("Giới Tính :");

        rdoNam_Khachhang.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        rdoNam_Khachhang.setText("Nam");

        rdoNu_Khachhang.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        rdoNu_Khachhang.setText("Nữ");

        txtHoTen_Khachhang.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtMa_Khachhang.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setText("Số ĐT :");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setText("CMND :");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setText("Email :");

        txtSoDT_Khachhang.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtCMND_Khachhang.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtEmail_Khachhang.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtHoTen_Khachhang, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                            .addComponent(txtMa_Khachhang)
                            .addComponent(txtNgaySinh_Khachhang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(71, 71, 71)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtCMND_Khachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSoDT_Khachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(33, 33, 33)
                                .addComponent(txtEmail_Khachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rdoNam_Khachhang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdoNu_Khachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(52, 52, 52)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCMND_Khachhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtHoTen_Khachhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMa_Khachhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(27, 27, 27)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txtEmail_Khachhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtNgaySinh_Khachhang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(txtSoDT_Khachhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdoNu_Khachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rdoNam_Khachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Edit"));

        btnThoat_Khachhang.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        btnThoat_Khachhang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Thoat-removebg-preview.png"))); // NOI18N
        btnThoat_Khachhang.setText("Thoát");
        btnThoat_Khachhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoat_KhachhangActionPerformed(evt);
            }
        });

        btnMoi_Khachhang.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        btnMoi_Khachhang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clear.png"))); // NOI18N
        btnMoi_Khachhang.setText("Mới   ");
        btnMoi_Khachhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoi_KhachhangActionPerformed(evt);
            }
        });

        btnXoa_Khachhang.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        btnXoa_Khachhang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N
        btnXoa_Khachhang.setText("Xoá   ");
        btnXoa_Khachhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa_KhachhangActionPerformed(evt);
            }
        });

        btnSua_Khachhang.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        btnSua_Khachhang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit.png"))); // NOI18N
        btnSua_Khachhang.setText("Sửa  ");
        btnSua_Khachhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSua_KhachhangActionPerformed(evt);
            }
        });

        btnThem_Khachhang.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        btnThem_Khachhang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        btnThem_Khachhang.setText("Thêm");
        btnThem_Khachhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem_KhachhangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnXoa_Khachhang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMoi_Khachhang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSua_Khachhang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThoat_Khachhang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThem_Khachhang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThem_Khachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSua_Khachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnXoa_Khachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMoi_Khachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnThoat_Khachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbl_Khachhang.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tbl_Khachhang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã", "Họ Tên", "Ngày Sinh", "Giới Tính", "Số ĐT", "CMND", "Email"
            }
        ));
        tbl_Khachhang.setRowHeight(30);
        tbl_Khachhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_KhachhangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_Khachhang);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 0));
        jLabel12.setText("Quản Lý Khách Hàng");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(415, 427, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addGap(415, 415, 415))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThoat_KhachhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoat_KhachhangActionPerformed
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_btnThoat_KhachhangActionPerformed

    private void btnMoi_KhachhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoi_KhachhangActionPerformed
        // TODO add your handling code here:
        moi();
    }//GEN-LAST:event_btnMoi_KhachhangActionPerformed

    private void btnSua_KhachhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSua_KhachhangActionPerformed
        // TODO add your handling code here:
        update();
    }//GEN-LAST:event_btnSua_KhachhangActionPerformed

    private void btnThem_KhachhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem_KhachhangActionPerformed
        // TODO add your handling code here:
        them();
    }//GEN-LAST:event_btnThem_KhachhangActionPerformed

    private void tbl_KhachhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_KhachhangMouseClicked
        // TODO add your handling code here:
        showDetail();
    }//GEN-LAST:event_tbl_KhachhangMouseClicked

    private void btnXoa_KhachhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoa_KhachhangActionPerformed
        // TODO add your handling code here:
        xoa();
    }//GEN-LAST:event_btnXoa_KhachhangActionPerformed
    
    
    DefaultTableModel myModel;
    public void filltotable() throws SQLException {
        myModel = (DefaultTableModel)tbl_Khachhang.getModel();
        myModel.setRowCount(0);
        String sql = "select * from KhachHang";
        Statement stt = ketnoi.con.createStatement();
        ResultSet rs = stt.executeQuery(sql);
        while(rs.next()) {
            String maKH = rs.getString("MaKH");
            String hoTen = rs.getString("TenKH");
            String ngaySinh = rs.getString("NgaySinhKH");
            String gioiTinh = rs.getString("GioiTinhKH");
            String SDT = rs.getString("SDTKH");
            String CMND = rs.getString("CMNDKH");
            String Email = rs.getString("EmailKH");
            myModel.addRow(new Object[]{maKH, hoTen, ngaySinh, gioiTinh, SDT, CMND, Email});
            listKH.add(new KhachHang(maKH, hoTen, ngaySinh, gioiTinh, SDT, CMND, Email));
        }
    }
    
    public boolean check() {
        if(txtMa_Khachhang.getText().length() == 0){
            JOptionPane.showMessageDialog(this, "Hãy điền mã khách hàng !");
            txtMa_Khachhang.requestFocus(true);
            return false;
        }
        for(KhachHang x : listKH) {
            if(txtMa_Khachhang.getText().equalsIgnoreCase(x.getMakh())){
                JOptionPane.showMessageDialog(this, "Mã khách hàng đã tồn tại");
                txtMa_Khachhang.requestFocus(true);
                return false;
            }
        }
        if(txtHoTen_Khachhang.getText().length() == 0){
            JOptionPane.showMessageDialog(this, "Hãy điền họ tên khách hàng !");
            txtHoTen_Khachhang.requestFocus(true);
            return false;
        }
        //Check Số điện thoại
        if(txtSoDT_Khachhang.getText().length() == 0){
            JOptionPane.showMessageDialog(this, "Hãy điền số điện thoại khách hàng !");
            txtSoDT_Khachhang.requestFocus(true);
            return false;
        }
        String sdtFormat = "0\\d{9}";
        if(!txtSoDT_Khachhang.getText().matches(sdtFormat)) {
            JOptionPane.showMessageDialog(this, "Số điện thoại có 10 số và đúng định dạng 0[1->9]");
            txtSoDT_Khachhang.requestFocus(true);
            return false;
        }
        for(KhachHang x : listKH) {
            if(txtSoDT_Khachhang.getText().equalsIgnoreCase(x.getSodt())){
                JOptionPane.showMessageDialog(this, "Số điện thoại đã tồn tại");
                txtSoDT_Khachhang.requestFocus(true);
                return false;
            }
        }
        if(txtCMND_Khachhang.getText().length() == 0){
            JOptionPane.showMessageDialog(this, "Hãy điền cmnd khách hàng !");
            txtCMND_Khachhang.requestFocus(true);
            return false;
        }
        String cmndFormat = "\\d{12}";
        if(!txtCMND_Khachhang.getText().matches(cmndFormat)) {
            JOptionPane.showMessageDialog(this, "CMND không hợp lệ !");
            txtCMND_Khachhang.requestFocus(true);
            return false;
        } 
        for(KhachHang x : listKH) {
            if(txtCMND_Khachhang.getText().equalsIgnoreCase(x.getCmnd())){
                JOptionPane.showMessageDialog(this, "CMND đã tồn tại");
                txtCMND_Khachhang.requestFocus(true);
                return false;
            }
        }
        if(txtEmail_Khachhang.getText().length() == 0){
            JOptionPane.showMessageDialog(this, "Hãy điền email khách hàng !");
            txtEmail_Khachhang.requestFocus(true);
            return false;
        }
        String emailFormat = "\\w+@gmail.com";
        if(!txtEmail_Khachhang.getText().matches(emailFormat)){
            JOptionPane.showMessageDialog(this, "Email không hợp lệ !");
            txtEmail_Khachhang.requestFocus(true);
            return false;
        }
        for(KhachHang x : listKH) {
             if(txtEmail_Khachhang.getText().equalsIgnoreCase(x.getEmail())){
                 JOptionPane.showMessageDialog(this, "Email đã tồn tại");
                 txtEmail_Khachhang.requestFocus(true);
                 return false;
             }
        }
        return true;
    }
    
    public void them() {
        if(check()) {
            String gt = null;
            if(rdoNam_Khachhang.isSelected()){
                gt = "Nam";
            }
            else{gt = "Nữ";}
            String maKH = txtMa_Khachhang.getText();
            String hoTen = txtHoTen_Khachhang.getText();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String ngaySinh = sdf.format(txtNgaySinh_Khachhang.getDate());
            String SDT = txtSoDT_Khachhang.getText();
            String CMND = txtCMND_Khachhang.getText();
            String Email = txtEmail_Khachhang.getText();
            try {
                String sql = "INSERT INTO KhachHang " +
                        "VALUES ('"+maKH.trim()+"',N'"+hoTen.trim()+"','"+ngaySinh.trim()+"',N'"+gt.trim()+"','"+SDT.trim()+"','"+CMND.trim()+"','"+Email.trim()+"')";
                Statement stt = ketnoi.con.createStatement();
                int rs = stt.executeUpdate(sql);
                listKH.add(new KhachHang(maKH, hoTen, ngaySinh, gt, SDT, CMND, Email));
                myModel.addRow(new Object[] {maKH, hoTen, ngaySinh, gt, SDT,CMND,Email}); 
                JOptionPane.showMessageDialog(this, "Thêm mới thành công");
                moi();
            } catch (HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(this, "Ngày sinh phải đúng định dạng yyyy-MM-dd");
            }
            
        }
    }
    
    public void moi() {
        btnThem_Khachhang.setEnabled(true);
        btnSua_Khachhang.setEnabled(false);
        btnXoa_Khachhang.setEnabled(false);
        tbl_Khachhang.clearSelection();
        txtMa_Khachhang.setText("");
        txtHoTen_Khachhang.setText("");
        try {
            Date date = new SimpleDateFormat("yyyy-MM-dd").parse("2020-01-10");
            txtNgaySinh_Khachhang.setDate(date);
        } catch (Exception e) {
        }
        rdoNam_Khachhang.setSelected(true);
        txtSoDT_Khachhang.setText("");
        txtEmail_Khachhang.setText("");
        txtCMND_Khachhang.setText("");
        txtMa_Khachhang.requestFocus(true);
        txtMa_Khachhang.setEditable(true);
    }
    
    public void xoa(){
        int chon = JOptionPane.showConfirmDialog(this, "Bạn chắc chắn muốn xóa ?");
        if(chon == 0){
            int i = tbl_Khachhang.getSelectedRow();
            try {
                String sql = "Delete KhachHang " +
                    "Where MaKH = '"+txtMa_Khachhang.getText().trim()+"'";
            Statement stt = ketnoi.con.createStatement();
            int rs = stt.executeUpdate(sql);
            listKH.remove(i);
            myModel.removeRow(i);
            moi();
            JOptionPane.showMessageDialog(this, "Đã Xóa");
            } catch (HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(this, "Không Thể Xóa Khách Hàng Này !");
                System.out.println(e);
            }
        }
    }
   
    public void update() {
        try {
           int row = tbl_Khachhang.getSelectedRow();
           KhachHang x = listKH.get(row);
           listKH.remove(row);
           String gioitinhKH;
           if(rdoNam_Khachhang.isSelected()) {
                    gioitinhKH = "Nam";
                }
                else{gioitinhKH = "Nữ";}
//            KhachHang x = new KhachHang((String)tbl_Khachhang.getValueAt(row, 0), (String)tbl_Khachhang.getValueAt(row, 1), (String)tbl_Khachhang.getValueAt(row, 2), gioitinhKH, (String)tbl_Khachhang.getValueAt(row, 4), (String)tbl_Khachhang.getValueAt(row, 5), (String)tbl_Khachhang.getValueAt(row, 6));
           if(check()){
                String maKH = txtMa_Khachhang.getText();
                String tenKH = txtHoTen_Khachhang.getText();
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String ngaysinhKH = sdf.format(txtNgaySinh_Khachhang.getDate());
                if(rdoNam_Khachhang.isSelected()) {
                    gioitinhKH = "Nam";
                }
                else{gioitinhKH = "Nữ";}
                String sdtKH = txtSoDT_Khachhang.getText();
                String cmndKH = txtCMND_Khachhang.getText();
                String emailKH = txtEmail_Khachhang.getText();
                listKH.add(row, new KhachHang(maKH, tenKH, ngaysinhKH, gioitinhKH, sdtKH, cmndKH, emailKH));
                
                String sql = "UPDATE KhachHang " +
                        "SET MaKH ='"+maKH.trim()+"',TenKH =N'"+tenKH.trim()+"',NgaySinhKH ='"+ngaysinhKH.trim()+"',GioiTinhKH =N'"+gioitinhKH.trim()+"',SDTKH ='"+sdtKH.trim()+"',CMNDKH ='"+cmndKH.trim()+"',EmailKH ='"+emailKH.trim()+"' " +
                        "WHERE MaKH ='"+maKH.trim()+"'";
                Statement stt = ketnoi.con.createStatement();
                int rs = stt.executeUpdate(sql); 
                
                myModel.setValueAt(txtMa_Khachhang.getText(), row, 0);
                myModel.setValueAt(txtHoTen_Khachhang.getText(), row, 1);
                myModel.setValueAt(ngaysinhKH, row, 2);
                myModel.setValueAt(gioitinhKH, row, 3);
                myModel.setValueAt(txtSoDT_Khachhang.getText(), row, 4);
                myModel.setValueAt(txtCMND_Khachhang.getText(), row, 5);
                myModel.setValueAt(txtEmail_Khachhang.getText(), row, 6);
                moi();
                JOptionPane.showMessageDialog(this, "Đã sửa");
           }
           else{
               listKH.add(row,x);
           }
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, "Ngày sinh phải đúng định dạng yyyy-MM-dd");
        }
    }
    public void showDetail() {
        txtMa_Khachhang.setEditable(false);
        index = tbl_Khachhang.getSelectedRow();
        txtMa_Khachhang.setText((String)myModel.getValueAt(index, 0));
        txtHoTen_Khachhang.setText((String)myModel.getValueAt(index, 1));
        try {
            Date date = new SimpleDateFormat("yyyy-MM-dd").parse((String)myModel.getValueAt(index, 2));
            txtNgaySinh_Khachhang.setDate(date);
        } catch (Exception e) {
        }
        txtSoDT_Khachhang.setText((String)myModel.getValueAt(index, 4));
        txtCMND_Khachhang.setText((String)myModel.getValueAt(index, 5));
        txtEmail_Khachhang.setText((String)myModel.getValueAt(index, 6));
        String gt = (String)myModel.getValueAt(index, 3);
        if(gt.equals("Nam")) {
            rdoNam_Khachhang.setSelected(true);
        }
        else{
            rdoNu_Khachhang.setSelected(true);
        }
        btnSua_Khachhang.setEnabled(true);
        btnXoa_Khachhang.setEnabled(true);
        btnThem_Khachhang.setEnabled(false);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMoi_Khachhang;
    private javax.swing.JButton btnSua_Khachhang;
    private javax.swing.JButton btnThem_Khachhang;
    private javax.swing.JButton btnThoat_Khachhang;
    private javax.swing.JButton btnXoa_Khachhang;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdoNam_Khachhang;
    private javax.swing.JRadioButton rdoNu_Khachhang;
    private javax.swing.JTable tbl_Khachhang;
    private javax.swing.JTextField txtCMND_Khachhang;
    private javax.swing.JTextField txtEmail_Khachhang;
    private javax.swing.JTextField txtHoTen_Khachhang;
    private javax.swing.JTextField txtMa_Khachhang;
    private com.toedter.calendar.JDateChooser txtNgaySinh_Khachhang;
    private javax.swing.JTextField txtSoDT_Khachhang;
    // End of variables declaration//GEN-END:variables
}
